title: "Cole Frank"
author: "Cole Frank"
description: "Research, odds, and ends"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: home}
#  - {file: "research.html", title: "Research", icon: flask}  # deactivated - uncomment when ready
  - {url: "https://substack.com/@colefrank", title: "Substack", icon: edit}
  - {url: "https://twitter.com/colevfrank", title: "Twitter", icon: twitter}
  - {url: "files/cvf_4_2023_resume.pdf", title: "Resume", icon: file}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:cole.v.frank@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/colevfrank"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
